[package]
name = "volantino"
version = "0.1.0"
authors = ["Enrico Stano <ocirne.onats@gmail.com>"]

[dependencies]
clap = "~2.32"
reqwest = "0.9.5"
select = "0.4.2"
serde_json = "1.0"
hubcaps = "0.5"
futures = "0.1.25"
tokio = "0.1.13"
